/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2022-05-20 03:46:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.test.BoardDTO;
import com.test.BoardDAO;
import com.util.DBConn;
import java.sql.Connection;

public final class Article_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.util.DBConn");
    _jspx_imports_classes.add("com.test.BoardDAO");
    _jspx_imports_classes.add("com.test.BoardDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String cp = request.getContextPath();

      out.write('\r');
      out.write('\n');

	Connection conn = DBConn.getConnection();
	BoardDAO dao = new BoardDAO(conn);
	
	// 이전 페이지(List.jsp → 목록 페이지)로부터 데이터(num, pageNum) 수신
	String pageNum = request.getParameter("pageNum");		//-- 페이지 번호
	String strNum = request.getParameter("num");			//-- 게시물 번호
	int num = Integer.parseInt(strNum);

	
	// 해당 게시물의 조회수 증가
	dao.updateHitCount(num);
	
	// 이전, 다음 게시물 번호 확인
	int beforeNum = dao.getBeforeNum(num);			//	??	22
	int nextNum = dao.getNextNum(num);				//		22	??	
	
	BoardDTO dtoBefore = null;
	BoardDTO dtoNext = null;
	
	if (beforeNum != -1)
		dtoBefore = dao.getReadData(beforeNum);
	
	if (nextNum != -1)
		dtoNext = dao.getReadData(nextNum);
	
	// 해당 게시물의 상세 내용 가져오기
	BoardDTO dto = dao.getReadData(num);
	
	// 게시물 본문 라인 수 확인
	int lineSu = dto.getContent().split("\n").length;
	
	// 게시물 내용
	dto.setContent(dto.getContent().replaceAll("\n", "<br>"));
	//-- 안녕하세요\n반갑습니다.\n즐거운오후입니다.\n안녕히가세요.
	//→ 안녕하세요<br>반갑습니다.<br>즐거운오후입니다.<br>안녕히가세요.
	
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Article.jsp</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp );
      out.write("/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cp );
      out.write("/css/article.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"bbs\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"bbs_title\">\r\n");
      out.write("\t\t게 시 판 (JDBC 연동 버전)\r\n");
      out.write("\t</div><!-- close #bbs_title  -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"bbsArticle\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"bbsArticle_header\">\r\n");
      out.write("\t\t\t\t<!-- 게시물의 제목입니다. -->\r\n");
      out.write("\t\t\t\t");
      out.print(dto.getSubject() );
      out.write("\r\n");
      out.write("\t\t</div><!-- close #bbsArticle_header  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"bbsArticle_bottomLine\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>작성자</dt>\r\n");
      out.write("\t\t\t\t<!-- <dd>김정용</dd> -->\r\n");
      out.write("\t\t\t\t<dd>");
      out.print(dto.getName() );
      out.write("</dd>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<dt>라인수</dt>\r\n");
      out.write("\t\t\t\t<!-- <dd>1</dd> -->\r\n");
      out.write("\t\t\t\t<dd>");
      out.print(lineSu );
      out.write("</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div><!-- close .bbsArticle_bottomLine  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"bbsArticle_bottomLine\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>등록일</dt>\r\n");
      out.write("\t\t\t\t<!-- <dd>2022-04-27</dd> -->\r\n");
      out.write("\t\t\t\t<dd>");
      out.print(dto.getCreated() );
      out.write("</dd>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<dt>조회수</dt>\r\n");
      out.write("\t\t\t\t<!-- <dd>13</dd> -->\r\n");
      out.write("\t\t\t\t<dd>");
      out.print(dto.getHitCount() );
      out.write("</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div><!-- close .bbsArticle_bottomLine  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"bbsArticle_content\">\r\n");
      out.write("\t\t\t<table style=\"width: 600;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"padding: 10px 40px 10px 10px; vertical-align: top; height: 150;\">\r\n");
      out.write("\t\t\t\t\t<!-- 어쩌구 저쩌구 이러쿵 저러쿵 내용입니다. -->\r\n");
      out.write("\t\t\t\t\t");
      out.print(dto.getContent() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div><!-- close #bbsArticle_content  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"bbsArticle_bottomLine\">\r\n");
      out.write("\t\t\t<!-- 이전글 : (104) 취미 관련 게시물 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			if (beforeNum != -1)
			{
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(cp);
      out.write("/Article.jsp?pageNum=");
      out.print(pageNum);
      out.write("&num=");
      out.print(beforeNum);
      out.write("\">\r\n");
      out.write("\t\t\t\t이전글 : (");
      out.print(beforeNum );
      out.write(')');
      out.write(' ');
      out.print(dtoBefore.getSubject());
      out.write("\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t");

			}
			else
			{
			
      out.write("\r\n");
      out.write("\t\t\t\t이전글 : 없음\r\n");
      out.write("\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div><!-- close .bbsArticle_bottomLine  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"bbsArticle_noLine\">\r\n");
      out.write("\t\t\t<!-- 다음글 : (102) 날씨 관련 게시물 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			if (nextNum != -1)
			{
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(cp);
      out.write("/Article.jsp?pageNum=");
      out.print(pageNum);
      out.write("&num=");
      out.print(nextNum);
      out.write("\">\r\n");
      out.write("\t\t\t\t다음글 : (");
      out.print(nextNum );
      out.write(')');
      out.write(' ');
      out.print(dtoNext.getSubject());
      out.write("\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

			}
			else
			{
			
      out.write("\r\n");
      out.write("\t\t\t\t다음글 : 없음\r\n");
      out.write("\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div><!-- end .bbsArticle_noLine  -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div><!-- close #bbsArticle  -->\t\t\t\t\t<!-- check~!!! -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"bbsArticle_noLine\" style=\"text-align: right;\">\r\n");
      out.write("\t\t<!-- From : 211.238.142.151 -->\r\n");
      out.write("\t\tFrom : ");
      out.print(dto.getIpAddr() );
      out.write("\r\n");
      out.write("\t</div><!-- close .bbsArticle_noLine  -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"bbsArticle_footer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"leftFooter\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"수정\" class=\"btn2\"\r\n");
      out.write("\t\t\tonclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/Updated.jsp?num=");
      out.print(dto.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("&status=1'\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"삭제\" class=\"btn2\"\r\n");
      out.write("\t\t\tonclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/Updated.jsp?num=");
      out.print(dto.getNum());
      out.write("&pageNum=");
      out.print(pageNum);
      out.write("&status=2'\">\r\n");
      out.write("\t\t</div><!-- close #leftFooter -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"rightFooter\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"리스트\" class=\"btn2\"\r\n");
      out.write("\t\t\tonclick=\"javascript:location.href='");
      out.print(cp);
      out.write("/List.jsp?pageNum=");
      out.print(pageNum);
      out.write("'\">\r\n");
      out.write("\t\t</div><!-- close #rightFooter -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div><!-- close #bbsArticle_footer  -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</div><!-- close #bbs -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
